const fs = require('fs');
let content = fs.readFileSync('src/data/hijaiyah.ts', 'utf8');

const replacements = [
  // Base Letters updates
  [/hint: "Garis lurus seperti tiang."/g, 'hint: "Garis lurus kayak tiang nih~."'],
  [/hint: "Seperti perahu, titik satu di bawah."/g, 'hint: "Bentuknya kayak perahu, titiknya satu di bawah nih~."'],
  [/hint: "Seperti perahu, senyum dengan titik dua di atas."/g, 'hint: "Bentuknya kayak perahu senyum nih, titiknya dua di atas~."'],
  [/hint: "Seperti perahu, titik tiga di atas. Ucapkan dengan ujung lidah."/g, 'hint: "Kayak perahu, titiknya tiga di atas. Bacanya pakai ujung lidah yaa~."'],
  [/hint: "Ada perut di bawah, titik satu di tengah."/g, 'hint: "Wah perutnya gendut di bawah, terus ada titiknya satu di tengah~."'],
  [/hint: "Sama seperti ja, tapi bersih tanpa titik."/g, 'hint: "Bentuknya sama persis kayak ja, tapi bersih nggak ada titiknya lho~."'],
  [/hint: "Sama seperti ja, tapi titiknya di atas."/g, 'hint: "Bentuknya sama kayak ja, tapi titiknya malah di atas nih~."'],
  [/hint: "Garis menekuk, tanpa titik."/g, 'hint: "Garisnya nekuk nih, dan polos nggak ada titiknya~."'],
  [/hint: "Seperti da, tapi ada titiknya satu di atas."/g, 'hint: "Bentuknya mirip da, tapi ini dikasih titik satu di atasnya~."'],
  [/hint: "Garis melengkung ke bawah, tidak ada titiknya."/g, 'hint: "Garisnya melengkung ke bawah, tapi nggak nempel titik sama sekali~."'],
  [/hint: "Bila tidak ada titiknya dibaca ro, ini ada titiknya di atas."/g, 'hint: "Bentuknya mirip ro, tapi yang ini punya topi (titik) di atasnya~."'],
  [/hint: "Punya gigi tiga, tanpa titik."/g, 'hint: "Wah giginya tiga nih, tapi nggak ada titiknya~."'],
  [/hint: "Punya gigi tiga, dengan tiga titik di atas."/g, 'hint: "Giginya tiga, terus titiknya juga tiga kompak banget tuh di atas~."'],
  [/hint: "Ada lubang agak bulat, tanpa titik."/g, 'hint: "Bentuknya agak bolong, dan bersih tanpa titik~."'],
  [/hint: "Seperti sho, tapi ada titik satu di atas."/g, 'hint: "Mirip banget sama sho, cuma bedanya ini dikasih titik satu di atasnya~."'],
  [/hint: "Ada kotak melingkar dan tiang, tanpa titik."/g, 'hint: "Ada tiangnya nih terus di bawahnya melingkar, dan polos tanpa titik~."'],
  [/hint: "Seperti tho, tapi dengan satu titik di atas."/g, 'hint: "Mirip sama tho, tapi ini malah dikasih titik satu di atas tiangnya~."'],
  [/hint: "Mulut terbuka ke kiri, tanpa titik."/g, 'hint: "Wah bentuknya kayak mulut lagi mangap ke kiri, dan nggak pakai titik~."'],
  [/hint: "Seperti \'a, tapi titiknya satu di atas."/g, 'hint: "Bentuknya mirip \\\'a\\\', tapi ada titik cantiknya satu di atas~."'],
  [/hint: "Punya kepala bulat, titik satu di atas."/g, 'hint: "Kepalanya bulat mungil, terus ada titik satu anteng di atasnya~."'],
  [/hint: "Seperti fa, tapi titiknya dua di atas."/g, 'hint: "Mirip lho sama fa, cuma titiknya yang ini ada dua di atas~."'],
  [/hint: "Garis siku dengan bentuk hamzah kecil di dalamnya."/g, 'hint: "Garis siku nih, terus ada bentuk hamzah kecil asik di dalemnya~."'],
  [/hint: "Garis lurus seperti kail pancing."/g, 'hint: "Bentuk kakinya panjang melesat ke bawah mirip alat pancing yaa~."'],
  [/hint: "Kepala bulat berlubang, ekor melengkung ke bawah."/g, 'hint: "Kepalanya bolong, terus ekornya melengkung ke bawah gitu~."'],
  [/hint: "Setengah lingkaran \(seperti mangkuk\), titik satu di tengah\/atas."/g, 'hint: "Bentuknya setengah lingkaran ala mangkuk, titiknya cuma ada separuh di atasnya~."'],
  [/hint: "Bentuk seperti huruf u atau angka sembilan."/g, 'hint: "Eh mirip huruf u atau angka sembilan ya bentuknya~."'],
  [/hint: "Bentuk bulat atau ikatan tali."/g, 'hint: "Bentuknya bulet lucu, atau kayak pita atau ikatan tali ya kempes~."'],
  [/hint: "Seperti angsa dengan dua titik di bawah."/g, 'hint: "Asoy badannya belok-belok mirip angsa putih, jangan lupa ada titik duanya di bawah~."'],
  [/hint: "Hamzah dengan harakat fathah, dibaca 'a'."/g, 'hint: "Hamzah mungil di atas, dibacanya \'a\' yaa~."'],
  [/hint: "Baca satu per satu secara berurutan"/g, 'hint: "Yuk, dibaca pelan-pelan satu per satu dari awal yaa~"'],

  // Iqra levels cleanup
  [/Mad Lazim Muthaqqal Kilmi/gi, 'Mad Lazim (Super Panjang)'],
  [/ditarik 6 ketukan/gi, 'ditarik puanjaaang (6 ayunan) yaa~'],
  [/panjang 6 ketukan/gi, 'ditarik puanjaaang (6 ayunan) yaa~'],
  [/Tarik 'Daa' 6 ketukan/gi, 'Tarik puanjaaang Daa nya (6 ayunan) yaa~'],
  [/6 harakat/gi, '6 ayunan panjangnya'],
  [/lalu tekan keras pada/gi, 'terus nabrak keras di huruf'],
  [/lalu ditabrak ke/gi, 'terus nabrak mantap ke huruf'],
  [/lalu menabrak/gi, 'terus nabrak ke huruf'],
  [/baru menekan kuat huruf/gi, 'terus tekan kuat hurufnya~'],
  [/Waqaf ta marbuthah.*jadi ha mati/gi, 'Kalau berhenti di ujung, berubah bunyinya jadi Ha lembut (mati) yaa~'],
  [/dengan sifat mendengkur/gi, 'bunyinya ikutan mendengkur gitu~'],
  [/dengan dengungan panjang menyengau/gi, 'sambil dengung nahan di hidung agak lama yaa~'],
  [/Waqaf pada/gi, 'Kalau berhentinya di huruf'],
  [/tekan Jim/gi, 'tekan mantap Jim-nya~'],
  [/tekan Nun dengung/gi, 'tekan Nun-nya sambil nahan dengung di hidung yaa~'],
  [/Kompleksitas tingkat tinggi!/gi, 'Wah lumayan panjang nih jebakannya, fokus yaa~'],
  [/Latihan Iqra 1-5:/gi, 'Latihan Campuran:'],
  [/Mad Jaiz(.*)Ikhfa(.*)Lafadz Allah Tafkhim .tebal\/loh.(.*)Gabungan hukum dasar hingga lanjutan./gi, 'Ditarik agak panjaang bacanya~ Ikhfa$1 Lafadz Allah dibaca tebal (loh)$2 Wah ini gabungan pelajaran dari awal sampai akhir, pasti bisa!'],
  [/Tasydid Nun .wajib dengung. dan Tasydid Ba .menekan tanpa dengung.\. Bedakan cara penekanannya!/gi, 'Nun kembar wajib dengungnya, Ba kembar ditekankan aja yaa~ Yuk cobain bedanya!'],
  [/Idgham Bighunnah/gi, 'Dilebur & Dengung'],
  [/Idgham Bilaghunnah/gi, 'Dilebur (Tapi Tanpa Dengung)'],
  [/Nun menabrak Nun dengan dengung hidung memanjang\. Ujung harakat Mad Aridh [^\.]*/gi, 'Nun-nya nyambung ke Nun lagi, dengungnya hidung agak lama yaa~ Di ujung kata ditarik panjaang mantap yaa~'],
  [/didengungkan/gi, 'sambil didengungkan yaa~'],
  [/sifat tengah leher saat menyuarakan/gi, 'suaranya agak ditekan dari tengah leher waktu kerasa huruf'],
  [/di kalimat ganda/gi, 'di 2 kata beda'],
  [/Fathatain menabrak Wau(.*)Tasydid Ha ditekan jelas(.*)/gi, 'Suara an-nya masuk lumer ke Wau ditahan dengung yaa~$1 Ha kembar dipertegas tekannya!$2'],
  [/Suara dhommatain langsung masuk Lam tanpa dengung\. Kaf hams ringan\./gi, 'Suara un-nya nabrak ke Lam tanpa tahan dengung di hidung yaa~ Kaf nya ngeluarin angin tipis (desis) yaa~'],
  [/Izhar Halqi/gi, 'Jelas Tanpa Dengung'],
  [/Izhar Syafawi/gi, 'Jelas di Bibir Tanpa Dengung'],
  [/Ikhfa Syafawi/gi, 'Dengung Samar Bibir Tutup'],
  [/di Nun mati bertemu(.*)dan Izhar(.*)di Mim mati\. Semua dibaca MURNI tanpa dengungan\./gi, 'waktu Nun mati ketemu$1 dan Mim mati gaboleh dengung ya! Langsug dibaca ngegas jelas, ga bertenDENGUNG sama sekali yaa~'],
  [/Mim sukun bertemu(.*)tahan dibibir tertutup sambil alirkan ke hidung/gi, 'Mim matinya mampir ke huruf$1 mulutnya nutup rapat terus didengung tipis keluar hidung yaa~'],
  [/Bacaan kompleks dengan variasi ghunnah dan makhraj\./gi, 'Panjang seru bacanya, ditarik nafas panjang~'],
  [/Shod fathah, Ra fathah\. Ta menabrak tasydid Lam Alif Lam Syamsiyah\. Konsisten tebal dan tipis huruf\./gi, 'Huruf Ta nabrak keras masuk ke Lam berkemah~ Ingat ya ada huruf yang tebal ada yang tipis~'],
  [/jangan mendengung! Waqaf di huruf Dal ujung menjadi Qalqalah Kubra terpantul/gi, 'jangan dengung! Pas berhenti, Dal nya dipantulin mantap uyy~'],
  [/Alif Lam Qomariyah jelas(.*)Ain dari tengah tenggorokan, diakhiri ta marbuthah(.*)/gi, 'Alif Lam Qomariyah tetap jelas$1 Huruf \'Ain dari tengah leher ditutup bunyi Ha di akhir lho~$2'],
  [/Sin sukun mengalir\. Lafadz Allah tarqiq tipis bersuara 'lah' karena didahului kasrah/gi, 'Huruf Sin matinya berdesis angin~ Lafadz Allah di sini lumayan tipis (lah) soalnya sebelumnya harakat kasrah yaa~'],
  [/Tahap Akhir Iqra 5: Qomariyah/gi, 'Yey akhir Iqra 5! Jelas bacaan Lam-nya'],
  [/Ghunnah Nun tasydid(.*)Syamsiyah wau tasydid(.*)berdengung, waqaf hams sin(.*)/gi, 'Nun kembar mendengung$1 Wau kembar mendengung$2 Berhenti pakai Sin berdesis angin~'],
  [/\(Pendek\): /g, ': '], // Clean up standard prefixes
  [/Nun sukun bertemu/gi, 'Nun mati ketemu sama'],
  [/Tekan dan tahan 2 harakat dengan suara sengau\/dengung\./gi, 'Ditekan, disulap lumer ditahan dengung (2 ayunan) lewat hidung yaa~'],
  [/Fathatain bertemu/gi, 'Garis dua di atas (an) mampir ke huruf'],
  [/Leburkan suara 'an' menjadi/gi, 'Suara an-nya disulap ganti jadi'],
  [/tahan 2 harakat lalu lafalkan/gi, 'tahan dengung 2 ayunan yaa~ baru nyebut'],
  [/Nun sukun bertemu Mim bertasydid(.*)Leburkan Nun dan dengungkan suara Mim 2 harakat\./gi, 'Nun mati ketemu Mim kembar$1 Nun matinya ditarik dlm dengung Mim lumayan lama yaa~'],
  [/Dhommatain bertemu(.*)Bunyi 'un' lebur dan berdengung seperti menahan/gi, 'Bunyi un mampir ke huruf$1 Suara un dimasukin ke dalam, terus tahan dengungnya asyik di'],
  [/Kasratain bertemu/gi, 'Bunyi in (garis dua bawah) ketemu huruf'],
  [/Leburkan 'in' ke/gi, 'Suara in disulap nyemplung masuk huruf'],
  [/dengungkan 2 harakat penuh\./gi, 'jangan pelit ya tarikan dengungnya pas 2 ayunan dums~'],
  [/Kalimat Panjang \(\d\):/g, 'Wow Kalimat Panjang!'],
  [/Perhatikan Fathatain pada/gi, 'Coba perhatiin garis dua atas (an) manis di huruf'],
  [/Tahan dengungannya/gi, 'Tahan asyik dengung pakai hidungnya'],
  [/Kasratain di/gi, 'Garis dua bawah seru di huruf'],
  [/melebur ke(.*)Tahan dan dengungkan dengan sempurna di bibir\./gi, 'dilabrak masuk ke huruf$1 Mingkem deh bibirnya terus asik didengung pakai hidung yaa~'],
  [/Memuat dua Idgham Bighunnah!/gi, 'Wah mantap dobel-dobel nih dengungnya!'],
  [/menabrak /gi, 'nyeruduk '],
  [/Di akhir ayat, Nun sukun masuk ke(.*)Ingat, Idgham Bighunnah wajib ditahan menyengau\./gi, 'Paling akhir, Nun mati nyambung asyik ke$1 Jangan lupa ditahan dengung hidung yaa~'],
  [/Lengkapi ketelitian pada tiap harakat panjang dan pendek tanpa terburu-buru\./gi, 'Bacanya slow aja ga butuh ngebut~ nikmatin bedanya panjang cepetnya~'],
  [/Iqlab :/gi, 'N/Tanwin Tuker Mim:'],
  [/Iqlab pada/gi, 'Tuker M pada'],
  [/N\/Tanwin Nabrak Ba \(Tukar Jadi Mim\)/gi, 'Tuker jadi Mim:'],
  [/Suara 'N' berubah menjadi Mim \('M'\)(.*)dan ditahan 2 harakat\./gi, 'Suara Nun nya diem aj ganti bunyi \'M\' yang diteken-teken manis~ ditahan 2 ayunan yaa~'],
  [/Nun sukun dalam satu kata bertemu Ba\. Nun mati berbalik jadi Mim mendengung\./gi, 'Satu gandengan nih, Nun mati ketemu Ba, jadi langsung dituker sama Mim mendengung yaa~'],
  [/Suara tanwin lebur ke Mim(.*)dan berdengung\./gi, 'Suara un nya sembunyi mantap di Mim$1 terus denguuuuunng~'],
  [/Kasratain bertemu Ba(.*)Bibir tertutup rapat menyuarakan letupan/gi, 'In ketemu Ba$1 Tutup deh bibirnya rapat buat bunyiin'],
  [/Fathatain berubah menjadi suara Mim yang mendengung ditahan\./gi, 'An nya diputer santuy lewat hidung kayak orang guman MM~ dan ditahan yaa~'],
  [/Perhatikan Nun sukun yang/gi, 'Fokus bentar! Punya Nun mati yang'],
  [/Tahan bibir menutup untuk membaca(.*)selama 2 harakat\./gi, 'Ayo mulutnya mingkem ditahan asyik buat bunyiin$1 (2 ayunan yaa)'],
  [/Selanjutnya disambung hukum/gi, 'Nanti dikasih temen susulan '],
  [/pada kata turunannya\./gi, 'di ujung lanjutannya ya~'],
  [/pada hamzah panjang bertemu/gi, 'di kata panjang nyrempet sama'],
  [/dengan rungan dengung hidung\./gi, 'sambil nikmatin dengung ngalir di idung yaa~'],
  [/bertemu Ba kasrah/gi, 'nyangkut ke huruf Ba kasrah'],
  [/Dengungan menahan suara(.*)merapat dengan jelas(.*)lalu Alif Lam dipantul tipis\./gi, 'Tahan seru suara dengung mulutnya pakai$1 mingkem anteng terus gas keluar~$2 Alif lam disentil santai yaa~'],
  [/Diakhiri bertemunya(.*)dengan(.*)Suara tanwin un wajib berbalik menjadi Mim mendengung sebelum masuk huruf Ba\./gi, 'Nanti nemu$1 ketemu sama huruf$2 Sulap ae bunyi un manja kemari jadi temen Mim asyik~'],
  
  // Some leftover uppercase PANJANG and PENDEK
  [/PANJANG/g, 'panjaang'],
  [/PENDEK/g, 'cepet aja'],

  [/di tengah/g, 'di dalem'],
  [/di akhir/g, 'paling ujung'],
  [/di awal/g, 'paling depan'],
  [/bersambung/g, 'gandengan'],
  [/Garis tegak di atas bacanya panjaang~, dan Ta/g, 'Alif panjang, dan Ta'],

  // Catch unreplaced uppercase ones:
  [/\(Ha\)/g, '(Haa)'],
  [/\(Dza\)/g, '(Dzaa)'],
  [/\(Baa\)/g, '(baa)'],
  [/\(Laa\)/g, '(laa)']
];

for (const [regex, replacement] of replacements) {
  content = content.replace(regex, replacement);
}

fs.writeFileSync('src/data/hijaiyah.ts', content);
console.log('Final hints updated successfully!');
